booktracker/booktracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

booktracker/main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('books/', views.book_index, name='book-index'),
    path('books/<int:book_id>/', views.book_detail, name='book-detail'),
    path('books/create', views.BookCreate.as_view(), name='book-create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
    path('books/<int:book_id>/add-page/', views.add_page, name='add-page'),
    path('accounts/signup/', views.signup, name='signup'),
]

booktracker/main_app/models.py
from django.db import models
from isbn_field import ISBNField
from django.urls import reverse
from django.contrib.auth.models import User

class Book(models.Model):
    title = models.CharField(max_length=1000)
    author = models.CharField(max_length=1000)
    date_of_publication = models.DateField('Publication Date')
    ISBN = ISBNField()
    user = models.ForeignKey (User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.title} by {self.author}'
    
    def get_absolute_url(self):
        return reverse("book-detail", kwargs={'book_id': self.id})

class Page(models.Model):
    # The Page number is Charfield because some pages are not integers but alphabetical, or use Roman numerals, etc.
    number = models.CharField(max_length=999999)
    content = models.CharField(max_length=1000)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f'Page {self.number} containing {self.content}'
    
    class Meta:
        ordering = ['number']

booktracker/main_app/forms.py
from django import forms
from .models import Page

class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ['number', 'content']

booktracker/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Book
from .forms import PageForm

class Home(LoginView):
    template_name = 'home.html'

@login_required
def book_index(request):
    books = Book.objects.filter(user=request.user)
    return render(request, 'books/index.html', {'books': books})

@login_required
def book_detail(request, book_id):
    book = Book.objects.get(id=book_id)
    page_form = PageForm()
    return render(request, 'books/detail.html', {'book': book, 'page_form': page_form})

class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'author', 'date_of_publication', 'ISBN']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = '/books/'

class BookUpdate(LoginRequiredMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'date_of_publication', 'ISBN']

class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = '/books/'

@login_required
def add_page(request, book_id):
    form = PageForm(request.POST)
    if form.is_valid():
        new_page = form.save(commit = False)
        new_page.book_id = book_id
        new_page.save()
    return redirect('book-detail', book_id = book_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('book-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

booktracker/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <title>Book Tracker</title>
    {% block head %} 
    {% endblock head %}
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}   
            <li><a href="{% url 'book-index' %}">All Books</a></li>
            <li><a href="{% url 'book-create' %}">Add a Book</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'home' %}">Login</a></li> 
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock content %}
     </main>
  </body>
</html>

booktracker/main_app/templates/books/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/books/book-detail.css' %}" />
{% endblock head %} 
{% block content %}
<section>
  <div class="book-details">
    <h1>Title: {{ book.title }}</h1>
    <h2>Author: {{ book.author }}</h2>
    <p>Published on {{ book.date_of_publication }}</p>
    <p>ISBN: {{ book.ISBN }}</p>
    <div class="cat-actions">
      <a href="{% url 'book-update' book.id %}" class="btn warn">Edit</a>
      <a href="{% url 'book-delete' book.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>
<section>
  <div class="pages">
    <h3>Add a new page:</h3>
    <form action="{% url 'add-page' book.id %}" method="post" autocomplete="off">
      {% csrf_token %}
      {{ page_form.as_p }}
      <button type="submit" class="btn submit">Add a page</button>
    </form>
    <h1>Pages:</h1>
    {% if book.page_set.all %}
    <ul>
      {% for page in book.page_set.all %}
      <li>Page {{ page.number }}: {{ page.content }}</li>
      {% endfor %}
    </ul>
    {% else %}
    <p><b>{{ book.title }}</b> has no pages added yet!</p>
    {% endif %}
  </div>
</section>
{% endblock content %}

booktracker/main_app/templates/books/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/books/book-index.css' %}"/>
{% endblock head %} 
{% block content %}

<section>
  <h1>Book List</h1>
</section>
<section class="card-container">
  {% for book in books %}
    <div class="card">
      <a href="{% url 'book-detail' book.id %}">
        <div class="card-content">
          <h2 class="card-title">{{ book.title }} by {{ book.author }}</h2>
          <p>Published on {{ book.date_of_publication }}</p>
          <p>ISBN: {{ book.ISBN }}</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>
{% endblock content %}

booktracker/main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock head %}
{% block content %}

<section>
  <div>
    <h1>This is the home page</h1>
  </div>
</section>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock content %}

booktracker/main_app/templates/main_app/book_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Book?</h1>
</div>

<h2>Are you sure you want to delete {{ book.title }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'book-detail' book.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock content %}

booktracker/main_app/templates/main_app/book_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock head %} 
{% block content %}

<div class="page-header">
  {% if book %}
    <h1>Edit {{ book.title }} by {{ book.author }}</h1>
  {% else %}
    <h1>Add a Book</h1>
  {% endif %}
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock content %}

booktracker/main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock head %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock content %}